/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/car1.glb --types --transform -o src/models/Car1_temp.tsx 
Files: public/car1.glb [5.63MB] > R:\Suhas\Blockrooms\client\src\models\car1-transformed.glb [760.01KB] (86%)
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/old-rusty-car-95baa20ebc5d4d2e869f0b549be838fe
Title: Old Rusty Car
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Object006_Material_#294_0']: THREE.Mesh
    ['Object007_Material_#295_0']: THREE.Mesh
    ['Plane001_Material_#316_0']: THREE.Mesh
  }
  materials: {
    Material_294: THREE.MeshStandardMaterial
    Material_295: THREE.MeshStandardMaterial
    Material_316: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Object006_Material_#294_0'].geometry} material={materials.Material_294} position={[0, -4.76, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Object007_Material_#295_0'].geometry} material={materials.Material_295} position={[0, -4.76, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Plane001_Material_#316_0'].geometry} material={materials.Material_316} position={[2.13, 0, -46.352]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car1-transformed.glb')
