/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/entity1.glb --types --transform -o src/models/Entity1_compressed.tsx
Files: public/entity1.glb [14.03MB] > entity1-transformed.glb [1.13MB] (92%)
Author: 🇧🇷 SamelCookies 🇧🇷 (https://sketchfab.com/ZamuelWarrior)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hound-backrooms-b835cbb0440942a0856da6cefd365d38
Title: Hound [Backrooms]
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

interface GLTFAction extends THREE.AnimationClip {
  name: string;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    Object_12: THREE.SkinnedMesh
    Object_14: THREE.SkinnedMesh
    Object_15: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_18: THREE.SkinnedMesh
    Object_20: THREE.SkinnedMesh
    Object_22: THREE.SkinnedMesh
    Object_24: THREE.SkinnedMesh
    Object_26: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_28: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/entity1-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} skeleton={nodes.Object_7.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_8.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_10.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_12.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_14.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_15.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_17.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_18.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_20.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_22.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_24.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_26.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_27.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
      <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_28.skeleton} position={[0, -0.179, -0.998]} rotation={[1.623, 0, 0]} scale={0.273} />
    </group>
  )
}

useGLTF.preload('/entity1-transformed.glb')
