/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shotgun.glb --types --transform -o src/models/Shotgun_temp.tsx 
Files: public/shotgun.glb [1.94MB] > R:\Suhas\Blockrooms\client\src\models\shotgun-transformed.glb [271.06KB] (86%)
Author: iedalton (https://sketchfab.com/iedalton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shotgun-b427092de61d4a0ca5943e56458eb83d
Title: Shotgun
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
  }
  materials: {
    Metal01: THREE.MeshStandardMaterial
    Wood_001: THREE.MeshStandardMaterial
    DarkSteel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shotgun-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Metal01} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Wood_001} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.DarkSteel} />
    </group>
  )
}

useGLTF.preload('/shotgun-transformed.glb')
