/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shotgunshoot.glb --types --transform -o src/models/Shotgunshoot_temp.tsx 
Files: public/shotgunshoot.glb [8.37MB] > R:\Suhas\Blockrooms\client\src\models\shotgunshoot-transformed.glb [1.19MB] (86%)
Author: Cransh (https://sketchfab.com/ccransh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fps-arms-remington-shotgun-e68ef617fe8a48cca8610d016ffd5881
Title: FPS Arms remington (shotgun)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|SG_FPS_Idle' | 'Armature|SG_FPS_Walk' | 'Armature|SG_FPS_Shot' | 'Armature|SG_FPS_Reload'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_90: THREE.SkinnedMesh
    Object_92: THREE.SkinnedMesh
    Object_94: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    material: THREE.MeshStandardMaterial
    remington: THREE.MeshStandardMaterial
    ['12ge']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/shotgunshoot-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material} skeleton={nodes.Object_90.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.remington} skeleton={nodes.Object_92.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['12ge']} skeleton={nodes.Object_94.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/shotgunshoot-transformed.glb')
