/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iedalton (https://sketchfab.com/iedalton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shotgun-b427092de61d4a0ca5943e56458eb83d
Title: Shotgun
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import MuzzleFlash from "../components/game/MuzzleFlash";

interface GLTFAction extends THREE.AnimationClip {
  name: string;
}

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
  }
  materials: {
    Metal01: THREE.MeshStandardMaterial
    Wood_001: THREE.MeshStandardMaterial
    DarkSteel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Shotgun(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF("/shotgun-transformed.glb") as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Metal01}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.Wood_001}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.DarkSteel}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/shotgun-transformed.glb")
