/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/table.glb --types --transform -o src/models/Table_temp.tsx 
Files: public/table.glb [11.6MB] > R:\Suhas\Blockrooms\client\src\models\table-transformed.glb [952.05KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8002: THREE.Mesh
    Object_6002: THREE.Mesh
    Object_9: THREE.Mesh
    Object_4004: THREE.Mesh
    defaultMaterial: THREE.Mesh
    defaultMaterial001: THREE.Mesh
    Object_4005: THREE.Mesh
  }
  materials: {
    Table_Kitchen_A: THREE.MeshStandardMaterial
    bullet_holder: THREE.MeshStandardMaterial
    ammo_body: THREE.MeshStandardMaterial
    ['material.005']: THREE.MeshStandardMaterial
    Material_001: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['material.006']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/table-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8002.geometry} material={materials.Table_Kitchen_A} position={[-2.272, 0, -8.66]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Object_6002.geometry} material={materials.bullet_holder} position={[-1.897, 0.79, -8.356]} rotation={[0, -0.759, 0]} scale={[0.037, 0.011, 0.056]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.ammo_body} position={[-1.595, 0.779, -8.488]} rotation={[0, -0.759, 0]} scale={[0.132, 0.093, 0.124]} />
      <mesh geometry={nodes.Object_4004.geometry} material={materials['material.005']} position={[-1.818, 0.804, -8.439]} rotation={[Math.PI / 2, 0, 0.759]} scale={[0.151, 0.116, 0.106]} />
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material_001} position={[-1.789, 0.798, -8.619]} rotation={[-3.065, -0.739, 0]} scale={[0.081, 0.107, 0.086]} />
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.039']} position={[-1.789, 0.8, -8.619]} rotation={[-3.065, -0.739, 0]} scale={[0.081, 0.107, 0.086]} />
      <mesh geometry={nodes.Object_4005.geometry} material={materials['material.006']} position={[-1.456, 0.8, -8.816]} rotation={[Math.PI / 2, 0, -0.455]} scale={[0.151, 0.116, 0.106]} />
    </group>
  )
}

useGLTF.preload('/table-transformed.glb')
