/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 talkie.glb --types 
Author: Ret.ouchs (https://sketchfab.com/ret.ouchs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walkie-talkie-9c491d6b0f9e42648fed6a049267db62
Title: Walkie talkie
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    rugged: THREE.MeshStandardMaterial
    display: THREE.MeshStandardMaterial
    main_mat: THREE.MeshStandardMaterial
    switches: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/talkie.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.rugged} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.display} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.main_mat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.switches} />
      </group>
    </group>
  )
}

useGLTF.preload('/talkie.glb')
